name: "discord-notify"
on: workflow_dispatch

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: Discord notification
        env:
          DISCORD_USERNAME: Subspace_Desktop-Releaser
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Subspace desktop version: ${{ steps.extract_version.outputs.version }} has been released! Check it out in this link: https://github.com/subspace/subspace-desktop/releases/tag/${{ steps.extract_version.outputs.version }}"
