name: "discord-notify"
on: workflow_dispatch

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_USERNAME: Subspace_Desktop-Releaser
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "TESTING: The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed."
